server:
  port: 80
cloud:
  aws:
    credentials:
      access-key: AKIAUNIWAT3BZDJVAJEE
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: taesik-uploaded-files

